//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ann.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ann.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple implementation commandline launcher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ann_Introduction {
            get {
                return ResourceManager.GetString("Ann_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Candidate Lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaxCandidateLines {
            get {
                return ResourceManager.GetString("MaxCandidateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_UpdateIndex {
            get {
                return ResourceManager.GetString("MenuItem_UpdateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activation Shortcut key is already in use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ActivationShortcutKeyIsAlreadyInUse {
            get {
                return ResourceManager.GetString("Message_ActivationShortcutKeyIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot open the index. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_IndexIsNotOpened {
            get {
                return ResourceManager.GetString("Message_IndexIsNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index is old. Update the index. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_IndexIsOld {
            get {
                return ResourceManager.GetString("Message_IndexIsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index not found. Update the index. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_IndexNotFound {
            get {
                return ResourceManager.GetString("Message_IndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index Updating... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_IndexUpdating {
            get {
                return ResourceManager.GetString("Message_IndexUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_InOpening {
            get {
                return ResourceManager.GetString("Message_InOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source Libraries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSourceLibraries {
            get {
                return ResourceManager.GetString("OpenSourceLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Activate {
            get {
                return ResourceManager.GetString("Settings_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add executable file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AddExecutableFile {
            get {
                return ResourceManager.GetString("Settings_AddExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AddFolder {
            get {
                return ResourceManager.GetString("Settings_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AddKey {
            get {
                return ResourceManager.GetString("Settings_AddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequently used folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_FrequentlyUsedFolders {
            get {
                return ResourceManager.GetString("Settings_FrequentlyUsedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Hide {
            get {
                return ResourceManager.GetString("Settings_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Stroke に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_KeyStroke {
            get {
                return ResourceManager.GetString("Settings_KeyStroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PriorityFiles {
            get {
                return ResourceManager.GetString("Settings_PriorityFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcuts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Shortcuts {
            get {
                return ResourceManager.GetString("Settings_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TargetFolders {
            get {
                return ResourceManager.GetString("Settings_TargetFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UserFolders {
            get {
                return ResourceManager.GetString("Settings_UserFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for updates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionChecker_Checking {
            get {
                return ResourceManager.GetString("VersionChecker_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download was completed. Version up at after restart. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionChecker_Downloaded {
            get {
                return ResourceManager.GetString("VersionChecker_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now downloading files... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionChecker_Downloading {
            get {
                return ResourceManager.GetString("VersionChecker_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ann is up to date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionChecker_Latest {
            get {
                return ResourceManager.GetString("VersionChecker_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot confirm the version update. Check Internet connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionChecker_Unknown {
            get {
                return ResourceManager.GetString("VersionChecker_Unknown", resourceCulture);
            }
        }
    }
}
